version: "3.8"
services:
  app:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
    networks:
      - backend
    container_name: backend-nodejs-container

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./app/.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - backend
    container_name: db-postgres-container

  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6739"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend

  redis-cli:
    image: "bitnami/redis:latest"
    command: ["redis-cli", "-h", "redis", "-p", "6379"]
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - backend
    container_name: redis-cli-container

networks:
  backend:
