version: "3.8"
services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./app:/src/app
    networks:
      - backend
    container_name: backend-nodejs-container

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - backend
    container_name: db-postgres-container
networks:
  backend:
